# Generated by Django 3.2.6 on 2023-10-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_oldcummulative_subjectstream'),
        ('publicsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTresult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub1', models.IntegerField(default=0)),
                ('sub2', models.IntegerField(default=0)),
                ('sub3', models.IntegerField(default=0)),
                ('sub4', models.IntegerField(default=0)),
                ('Total', models.IntegerField(default=0)),
                ('entrydate', models.CharField(default='00-00-000', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
                ('subject1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='accounts.subjects')),
                ('subject2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='accounts.subjects')),
                ('subject3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='accounts.subjects')),
                ('subject4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='accounts.subjects')),
            ],
            options={
                'ordering': ('-entrydate',),
            },
        ),
    ]
