# Generated by Django 3.2.6 on 2022-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220328_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admission_ses',
            field=models.IntegerField(default=1),
        ),
    ]
