# Generated by Django 3.2.6 on 2022-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lessionplan_session_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='classaverage',
            name='p_comment',
            field=models.TextField(default='An excellent performance. There is always room for improvement.'),
        ),
        migrations.AddField(
            model_name='classaverage',
            name='t_comment',
            field=models.TextField(default='Excellent performance. Keep it up and more.'),
        ),
    ]
