# Generated by Django 3.2.6 on 2024-03-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_item_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity_after_entry',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity_at_entry',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
