# Generated by Django 3.2.6 on 2024-05-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20240319_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteControls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('c_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
