# Generated by Django 3.2.6 on 2024-05-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_countvalue_sitecontrols_count_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryAttestation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=255)),
                ('result_type', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sessionyearmodel')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
            ],
        ),
    ]
