# Generated by Django 3.2.6 on 2024-12-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_gncresponse_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classaverage',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
