# Generated by Django 3.2.6 on 2025-03-13 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_studymaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_pdf', models.FileField(upload_to='exam_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classes')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sessionyearmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
            ],
        ),
    ]
