# Generated by Django 3.2.6 on 2022-03-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_oldresults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldresults',
            old_name='students_id',
            new_name='students',
        ),
    ]
