# Generated by Django 3.2.6 on 2022-03-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_rename_students_id_oldresults_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldresults',
            name='classes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.classes'),
        ),
    ]
