"""
Django settings for chs_Website project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config
<<<<<<< HEAD

=======
import mimetypes
mimetypes.add_type("text/css", ".css", True)
>>>>>>> 869102c69b442947ca113121ce958681c2b69674

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c8)eneh%b$xi$4@je&#keewd_1*!e^z10s*_f5)l95#ldqg-5+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["christhighschool.org","www.christhighschool.org"]

MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"media")


STATIC_URL="/static/"
STATIC_ROOT=os.path.join(BASE_DIR,"static")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'captcha',
    'onlinecbt',
    'publicsite',
    'hostel',
<<<<<<< HEAD
    'paystackpayments',
    'rest_framework'
=======
    'onlinecbt',
    'paystackpayments'
>>>>>>> 869102c69b442947ca113121ce958681c2b69674
]

MIDDLEWARE = [
    #enable white only when making live
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.LoginCheckMiddleWare.LoginCheckMiddleware'
]

ROOT_URLCONF = 'chs_Website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['accounts/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chs_Website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        #enable only when making live
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE':'django.db.backends.mysql',
        'NAME':'chrijpdc_chswebsite',
        'USER':'chrijpdc_jimmy4carter',
        'PASSWORD':'jimmycarter12.',
        'HOST':'localhost',
        'PORT':'3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

PAYSTACK_SECRET_KEY=config('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY=config('PAYSTACK_PUBLIC_KEY')


RECAPTCHA_PUBLIC_KEY = '6Lc3a4ooAAAAABuolxTT7iDcPxejtEOgeslisJqw'
RECAPTCHA_PRIVATE_KEY = '6Lc3a4ooAAAAAFa-usWPyNpCe9-9Oi_0ji2zFK2F'

AUTH_USER_MODEL="accounts.CustomUser"
AUTHENTICATE_BACKENDS=['accounts.EmailBackEnd.EmailBackEnd']

# EMAIL_BACKEND="django.core.mail.backends.filebased.EmailBackend"
# EMAIL_FILE_PATH=os.path.join(BASE_DIR,"sent_mails")



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.christhighschool.org'
# EMAIL_HOST = 'smtp.business134.web-hosting.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL=False
EMAIL_HOST_USER = 'info@christhighschool.org'
EMAIL_HOST_PASSWORD = 'jimmycarter12.'
<<<<<<< HEAD
=======
# DEFAULT_FROM_EMAIL='info@christhighschool.org'
# RECIPIENT_ADDRESS='www.jimmy000carter@gmail.com'
>>>>>>> 869102c69b442947ca113121ce958681c2b69674


#enable only when making life
# STATICFILES_STORAGE='whitenoise.storage.CompressedManifestStaticFilesStorage'
# import dj_database_url
# prod_db=dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(prod_db)