# Generated by Django 3.2.6 on 2022-02-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('event_year', models.CharField(max_length=255)),
                ('event_month', models.CharField(max_length=255)),
                ('event_day', models.CharField(max_length=255)),
                ('future_image', models.FileField(upload_to='')),
                ('event_location', models.CharField(max_length=255)),
                ('blog_post', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('letter', models.FileField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
