# Generated by Django 3.2.6 on 2024-05-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_entryattestation'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEthosRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leadership', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('neatness', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('room_represent_compet', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('room_represent_inspect', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('selfconfidence', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('team_spirit', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('return_lost_items', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('obidience_to_staff', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('obidience_to_rules', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('volunteerism', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('reporting_unacceptable_behavior', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('prayerfullness', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0)),
                ('loitering', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('immoral_relation_conduct', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('poor_timing', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('negative_influence', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('noise_making', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('hostel_disobidience', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('bullying_fighting', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('negative_civil', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('gossip', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('avoiding_meals', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('carelessness_personal', models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('result_type', models.PositiveSmallIntegerField(choices=[(1, 'First Half'), (2, 'End of Term')], default=0)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sessionyearmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
            ],
        ),
    ]
