# Generated by Django 3.2.6 on 2024-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_studentethosrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentethosrecords',
            name='avoiding_meals',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='bullying_fighting',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='carelessness_personal',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='gossip',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='hostel_disobidience',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='immoral_relation_conduct',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='leadership',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='loitering',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='neatness',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='negative_civil',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='negative_influence',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='noise_making',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='obidience_to_rules',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='obidience_to_staff',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='poor_timing',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Very Poor'), (3, 'Bad'), (4, 'Very Bad'), (5, 'Very Very Bad')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='prayerfullness',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='return_lost_items',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='room_represent_compet',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='room_represent_inspect',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='selfconfidence',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='team_spirit',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
        migrations.AlterField(
            model_name='studentethosrecords',
            name='volunteerism',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=0),
        ),
    ]
