# Generated by Django 3.2.6 on 2024-05-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_entryattestation'),
        ('hostel', '0003_auto_20240513_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentethosrecords',
            unique_together={('student_id', 'term', 'session_year', 'result_type')},
        ),
    ]
