# Generated by Django 3.2.6 on 2023-02-28 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecbt', '0003_quiz_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ending date and time of the quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Starting date and time of the quiz'),
        ),
    ]
