# Generated by Django 3.2.6 on 2023-02-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_students_admission_ses'),
        ('onlinecbt', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects'),
            preserve_default=False,
        ),
    ]
