# Generated by Django 3.2.6 on 2022-03-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_oldresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='feedbackstudent',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='studentexitreport',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='LessionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weeks', models.CharField(max_length=255)),
                ('plan_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
