# Generated by Django 3.2.6 on 2022-05-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_students_admission_ses'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsAllo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('class_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classcategories')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
