# Generated by Django 3.2.6 on 2022-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221125_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
