# Generated by Django 3.2.6 on 2023-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessionplan',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
