# Generated by Django 3.2.6 on 2023-06-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_combineendterm_combinemidterm_combinesubjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=20)),
                ('subj_choice', models.TextField()),
                ('career1', models.CharField(max_length=100)),
                ('career2', models.CharField(max_length=100)),
                ('career3', models.CharField(max_length=100)),
                ('reason1', models.TextField()),
                ('passsubj1', models.CharField(max_length=100)),
                ('passsubj2', models.CharField(max_length=100)),
                ('passsubj3', models.CharField(blank=True, max_length=100)),
                ('passsubj4', models.CharField(blank=True, max_length=100)),
                ('passsubj5', models.CharField(blank=True, max_length=100)),
                ('passsubj6', models.CharField(blank=True, max_length=100)),
                ('failsubj1', models.CharField(max_length=100)),
                ('failsubj2', models.CharField(max_length=100)),
                ('failsubj3', models.CharField(blank=True, max_length=100)),
                ('failsubj4', models.CharField(blank=True, max_length=100)),
                ('failsubj5', models.CharField(blank=True, max_length=100)),
                ('failsubj6', models.CharField(blank=True, max_length=100)),
                ('pcareer', models.CharField(max_length=100)),
                ('preason', models.TextField()),
                ('pname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('parentcode', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.CreateModel(
            name='OldCummulative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cummulative_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sessionyearmodel')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
    ]
