# Generated by Django 3.2.6 on 2024-02-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_damagereport_item_stock_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='package_type',
            field=models.CharField(choices=[('box', 'Box'), ('bag', 'BAG'), ('crate', 'CRATE'), ('satchets', 'SATCHETS'), ('carton', 'CARTON'), ('pieces', 'PIECES'), ('jarican', 'JARICAN'), ('measure', 'MEASURE'), ('roll', 'ROLL'), ('tray', 'TRAY'), ('kilo', ' KILO'), ('packs', 'PACKS'), ('tin', 'TIN'), ('gram', 'GRAMS')], max_length=50),
        ),
    ]
