# Generated by Django 3.2.6 on 2024-03-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_item_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='package_type',
            field=models.CharField(choices=[('box', 'Box'), ('bag', 'BAG'), ('crate', 'CRATE'), ('satchets', 'SATCHETS'), ('carton', 'CARTON'), ('pieces', 'PIECES'), ('jarican', 'JARICAN'), ('measure', 'MEASURE'), ('roll', 'ROLL'), ('tray', 'TRAY'), ('kilo', ' KILO'), ('packs', 'PACKS'), ('tin', 'TIN'), ('gram', 'GRAMS'), ('litre', 'LITRE'), ('bunch', 'BUNCH'), ('tubers', 'TUBERS'), ('crowns', 'CROWNS'), ('slices', 'SLICES'), ('cups', 'CUPS'), ('baskets', 'BASKETS'), ('foot', 'FOOT')], max_length=50),
        ),
    ]
