# Generated by Django 3.2.6 on 2024-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sitecontrols'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontrols',
            name='countvalue',
            field=models.IntegerField(default=0),
        ),
    ]
