# Generated by Django 3.2.6 on 2024-05-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_sitecontrols_countvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontrols',
            old_name='countvalue',
            new_name='count_value',
        ),
    ]
