# Generated by Django 3.2.6 on 2024-05-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_entryattestation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entryattestation',
            unique_together={('term', 'session_year', 'result_type', 'subjects')},
        ),
    ]
