# Generated by Django 3.2.6 on 2024-05-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_gncresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gncresponse',
            unique_together={('student', 'question')},
        ),
    ]
