# Generated by Django 3.2.6 on 2025-02-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_notificationapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('note', 'Note'), ('assignment', 'Assignment'), ('textbook', 'Textbook')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subjects')),
            ],
        ),
    ]
