# Generated by Django 3.2.6 on 2022-03-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20220206_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_type', models.IntegerField(default=0)),
                ('result_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sessionyearmodel')),
                ('students_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.terms')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
