# Generated by Django 3.2.6 on 2022-03-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20220326_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessionplan',
            old_name='profile_pic',
            new_name='plan_file',
        ),
    ]
