# Generated by Django 3.2.6 on 2022-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_rename_profile_pic_lessionplan_plan_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='admission_class',
            new_name='admission_ses',
        ),
    ]
