# Generated by Django 3.2.6 on 2022-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_admission_class_students_admission_ses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_ses',
            field=models.IntegerField(default=1),
        ),
    ]
