# Generated by Django 3.2.6 on 2022-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_students_admission_ses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='admission_ses',
        ),
        migrations.AddField(
            model_name='students',
            name='admission_class',
            field=models.IntegerField(default=0),
        ),
    ]
