# Generated by Django 3.2.6 on 2022-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20220405_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admission_ses',
            field=models.IntegerField(default=0),
        ),
    ]
