# Generated by Django 3.2.6 on 2022-09-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='qualification',
        ),
    ]
