# Generated by Django 3.2.6 on 2022-09-01 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20220901_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Sex',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
